name: Unity CI/CD

on:
  push:
    branches: [ jetha ] # Trigger on pushes to the main branch
    tags:
      - 'buildtest'
      - 'v*.*.*' # Trigger on version tags like v1.0.0
  pull_request:
    branches: [ jetha ] # Trigger on pull requests to the main branch
  workflow_dispatch: # Allow manual triggering

jobs:
  build-windows: # Renamed job
    name: Build Unity Project (Windows) # Updated name
    runs-on: ubuntu-latest # Unity builds are generally faster on Linux runners
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true # Required for Unity projects using Git LFS

      # Cache
      - name: Cache Library folder
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Download and Extract Gemma Model from Kaggle
      - name: Download and Extract Gemma Model
        run: |
          echo "Installing Kaggle CLI..."
          pip install kaggle --upgrade
          echo "Configuring Kaggle credentials..."
          mkdir -p ~/.kaggle
          echo '{"username":"${{ secrets.KAGGLE_USERNAME }}","key":"${{ secrets.KAGGLE_KEY }}"}' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
          echo "Creating target directory..."
          mkdir -p Assets/StreamingAssets/gemma-3.0-4b
          echo "Downloading Gemma model..."
          # Use the correct command structure including version number /1
          kaggle models instances versions download google/gemma-3/gemmaCpp/3.0-4b-it-sfp/1 -p . --quiet
          echo "Extracting Gemma model (gemma-3.tar.gz)..."
          mkdir -p Assets/StreamingAssets/gemma-3.0-4b
          # Extract the downloaded tar.gz file
          if [ -f "gemma-3.tar.gz" ]; then
            tar -xzf gemma-3.tar.gz -C Assets/StreamingAssets/gemma-3.0-4b
            # Optional: Remove the tar.gz file after extraction
            # rm gemma-3.tar.gz
          else
            echo "Error: Could not find downloaded model file gemma-3.tar.gz."
            exit 1
          fi
          echo "Model download and extraction complete."
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

      # Unity Builder
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          buildName: GemmaJourney # Name of the executable

      # Output Build Path
      - name: Get Build Output Path
        id: build_path
        run: echo "path=$(ls -d build/StandaloneWindows64/* | head -n 1)" >> $GITHUB_OUTPUT

      # Zip build
      - name: Zip Build Artifact
        run: zip -r windows-build.zip ${{ steps.build_path.outputs.path }}

      # Upload Artifact (Optional, but good for debugging/accessing build from non-release runs)
      - name: Upload Build Artifact (Zip)
        uses: actions/upload-artifact@v4
        with:
          name: build-windows-zipped
          path: windows-build.zip

      # Create Release and Upload
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v') # Only run for tags starting with 'v'
        uses: softprops/action-gh-release@v1
        with:
          files: windows-build.zip # Attach the zip file to the release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, no need to create it
